---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-agent-octopus-com-v1beta1-workloadserviceaccount
  failurePolicy: Fail
  name: vworkloadserviceaccount-v1beta1.kb.io
  rules:
  - apiGroups:
    - agent.octopus.com
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    resources:
    - workloadserviceaccounts
  sideEffects: None
