---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - agent.octopus.com
  resources:
  - workloadserviceaccounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - agent.octopus.com
  resources:
  - workloadserviceaccounts/finalizers
  verbs:
  - update
- apiGroups:
  - agent.octopus.com
  resources:
  - workloadserviceaccounts/status
  verbs:
  - get
  - patch
  - update
