apiVersion: agent.octopus.com/v1beta1
kind: WorkloadServiceAccount
metadata:
  name: test-resource
  namespace: default
spec:
  scope:
    projects:
      - Liam
    environments:
      - Development
    steps:
      - "*"
    spaces:
      - "test-space"
  permissions:
    clusterRoles:
      - apiGroup: "rbac.authorization.k8s.io"
        kind: "ClusterRole"
        name: "test-cluster-role"