apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: octopus-permissions-controller
    app.kubernetes.io/managed-by: kustomize
  name: system