name: E2E Tests

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test-e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        uses: actions/checkout@v4

      - name: Check for code changes
        id: changes
        uses: tj-actions/changed-files@v47
        with:
          files: |
            **.go
            go.mod
            go.sum
            Makefile
            config/**

      - name: Setup Go
        if: steps.changes.outputs.any_changed == 'true'
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Install the latest version of kind
        if: steps.changes.outputs.any_changed == 'true'
        run: |
          curl -Lo ./kind https://kind.sigs.k8s.io/dl/latest/kind-linux-amd64
          chmod +x ./kind
          sudo mv ./kind /usr/local/bin/kind

      - name: Verify kind installation
        if: steps.changes.outputs.any_changed == 'true'
        run: kind version

      - name: Running Test e2e
        if: steps.changes.outputs.any_changed == 'true'
        run: |
          go mod tidy
          make test-e2e
